version: '3.8'

services:
  web:
    image: php:7.4-apache
    container_name: lfi-rce-ctf
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    restart: always
